### ISSUE TITLE
Idk 

### ISSUE THREAD

**Issue by rpdiss** [hex13/atom-lupa#1]
[Enter steps to reproduce below:]
1. pressed toggle in menu...
2. ...

**Atom Version**: 1.5.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-lupa](https://github.com/hex13/atom-lupa) package, v0.3.1
### Stack Trace

Failed to activate the atom-lupa package

```
At ENOENT: no such file or directory, open 'C:\Users\lukasz\output.json'

Error: ENOENT: no such file or directory, open 'C:\Users\lukasz\output.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at Object.<anonymous> (file:///C:/Users/rpiekarski/.atom/packages/atom-lupa/lib/init.coffee:19:11)
    at Object.<anonymous> (file:///C:/Users/rpiekarski/.atom/packages/atom-lupa/lib/init.coffee:14:1)
    at Module._compile (C:\Users\rpiekarski\AppData\Local\atom\app-1.5.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\rpiekarski\AppData\Local\atom\app-1.5.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\rpiekarski\AppData\Local\atom\app-1.5.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.module.exports.AtomLupa.activate (file:///C:/Users/rpiekarski/.atom/packages/atom-lupa/lib/atom-lupa.coffee:11:14)
    at Package.module.exports.Package.activateNow (C:\Users\rpiekarski\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package.js:181:20)
    at C:\Users\rpiekarski\AppData\Local\atom\app-1.5.3\resources\app.asar\src\package.js:800:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\rpiekarski\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\rpiekarski\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\rpiekarski\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:241:20)
    at CommandRegistry.handleCommandEvent (C:\Users\rpiekarski\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\rpiekarski\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\rpiekarski\AppData\Local\atom\app-1.5.3\resources\app.asar\src\atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -0:01.6.0 atom-lupa:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [],
    "themes": [
      "one-dark-ui",
      "an-old-hope-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
an-old-hope-syntax, v0.5.0
angularjs, v0.3.4
atom-lupa, v0.3.1
autocomplete-html-entities, v0.1.0
autocomplete-json, v1.5.0
color-picker, v2.1.1
debugger, v0.0.1
file-icons, v1.6.14
highlight-line, v0.11.1
linter, v1.11.3
linter-jshint, v1.3.1
linter-tidy, v2.1.0
minimap, v4.19.0
nuclide, vundefined
pigments, v0.23.1
react, v0.14.1

# Dev
No dev packages
```

**Comment by hex13** [comment]
thanks. fixed :)

**Comment by rpdiss** [comment]
needed to cut because of nda check screen...
![image](https://cloud.githubusercontent.com/assets/9515082/13397889/2897b9b4-defc-11e5-8919-51278ba70b01.png)

**Comment by hex13** [comment]
ok, I've added (very basic for now) support for HTML files:  
![image](https://cloud.githubusercontent.com/assets/3883359/13435091/d5f96c9c-dfd8-11e5-8d06-760cebacaef6.png)
