### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buffer' of undefined

### ISSUE THREAD

**Issue by dcplatforms** [hex13/atom-lupa#16]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.4
**Thrown From**: [atom-lupa](https://github.com/hex13/atom-lupa) package, v0.5.36
### Stack Trace

Uncaught TypeError: Cannot read property 'buffer' of undefined

```
At /Users/Cal/.atom/packages/atom-lupa/lib/atom-bindings/atom-main.js:106

TypeError: Cannot read property 'buffer' of undefined
    at updateEditor (/Users/Cal/.atom/packages/atom-lupa/lib/atom-bindings/atom-main.js:106:27)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:560:16)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:637:16)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:688:17)
```
### Commands

```
     -2:22.4.0 atom-lupa:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:16.3.0 application:add-project-folder (input.lupa-search)
 12x -1:06.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode)
     -1:01.4.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
 56x -1:00.4.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angular-jonpapa-snippets, v0.7.0
angularjs, v0.3.4
atom-html-preview, v0.1.19
atom-lupa, v0.5.36
atomic-chrome, v0.3.0
autocomplete-angular-material, v0.4.0
autocomplete-json, v1.11.0
emmet, v2.4.3
file-icons, v1.7.12
formatter-tidy, v1.0.1
js-refactor, v0.6.0
json-schema, v0.1.15
minimap, v4.24.2
npm, v0.1.0
pigments, v0.27.1
prime-file-icons, v0.2.2
refactor, v0.6.0
serverspec-snippets, v0.1.1
template-generator, v0.12.2
template-insert, v2.0.3
tokamak-terminal, v0.1.1
vim-mode, v0.65.1

# Dev
No dev packages
```

**Comment by hex13** [comment]
`TypeError: Cannot read property 'buffer' of undefined
    at updateEditor (/Users/Cal/.atom/packages/atom-lupa/lib/atom-bindings/atom-main.js:106:27)`

So it should check if editor exists before checking buffer... 

Ok. Updated.
