### ISSUE TITLE
Not working with Atom v1.12.2

### ISSUE THREAD

**Issue by amandeepmittal** [hex13/atom-lupa#38]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.2
**Electron Version**: 1.3.6
**System**: Mac OS X 10.12.1
**Thrown From**: [atom-lupa](https://github.com/hex13/atom-lupa) package, v0.7.25

### Stack Trace

Uncaught TypeError: Cannot read property 'RemovePreview' of undefined

```
At /Users/amandeepmittal/.atom/packages/atom-lupa/node_modules/react/lib/ReactErrorUtils.js:52

TypeError: Cannot read property 'RemovePreview' of undefined
    at onBlur (/Users/amandeepmittal/.atom/packages/atom-lupa/lib/components/Lupa.js:132:34)
    at Object.invokeGuardedCallback (/Users/amandeepmittal/.atom/packages/atom-lupa/node_modules/react/lib/ReactErrorUtils.js:26:12)
    at executeDispatch (/Users/amandeepmittal/.atom/packages/atom-lupa/node_modules/react/lib/EventPluginUtils.js:89:21)
    at Object.executeDispatchesInOrder (/Users/amandeepmittal/.atom/packages/atom-lupa/node_modules/react/lib/EventPluginUtils.js:112:5)
    at executeDispatchesAndRelease (/Users/amandeepmittal/.atom/packages/atom-lupa/node_modules/react/lib/EventPluginHub.js:44:22)
    at executeDispatchesAndReleaseTopLevel (/Users/amandeepmittal/.atom/packages/atom-lupa/node_modules/react/lib/EventPluginHub.js:55:10)
    at Array.forEach (native)
    at forEachAccumulated (/Users/amandeepmittal/.atom/packages/atom-lupa/node_modules/react/lib/forEachAccumulated.js:25:9)
    at Object.processEventQueue (/Users/amandeepmittal/.atom/packages/atom-lupa/node_modules/react/lib/EventPluginHub.js:231:7)
    at runEventQueueInBatch (/Users/amandeepmittal/.atom/packages/atom-lupa/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.handleTopLevel [as _handleTopLevel] (/Users/amandeepmittal/.atom/packages/atom-lupa/node_modules/react/lib/ReactEventEmitterMixin.js:29:5)
    at handleTopLevelImpl (/Users/amandeepmittal/.atom/packages/atom-lupa/node_modules/react/lib/ReactEventListener.js:73:24)
    at ReactDefaultBatchingStrategyTransaction.perform (/Users/amandeepmittal/.atom/packages/atom-lupa/node_modules/react/lib/Transaction.js:138:20)
    at Object.batchedUpdates (/Users/amandeepmittal/.atom/packages/atom-lupa/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
    at Object.batchedUpdates (/Users/amandeepmittal/.atom/packages/atom-lupa/node_modules/react/lib/ReactUpdates.js:98:20)
    at dispatchEvent (/Users/amandeepmittal/.atom/packages/atom-lupa/node_modules/react/lib/ReactEventListener.js:150:20)
```

### Commands

```
     -0:50.8.0 atom-lupa:focus (select#atom-lupa.sorting.form-control)
  2x -0:35.8.0 atom-lupa:toggle (div.package-detail.panels-item)
     -0:22 settings-view:open (input.lupa-search.native-key-bindings)
     -0:13.6.0 core:cancel (div.package-detail.panels-item)
     -0:11.7.0 atom-lupa:focus (div.package-detail.panels-item)
  2x -0:09.8.0 atom-lupa:toggle (input.lupa-search.native-key-bindings)
  5x -0:01.7.0 atom-lupa:focus (div.package-detail.panels-item)
     -0:00.0 atom-lupa:toggle (input.lupa-search.native-key-bindings)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "metrics",
      "language-c",
      "autosave"
    ],
    "telemetryConsent": "no"
  },
  "atom-lupa": {
    "breadcrumbsAlwaysVisible": true,
    "positionOfBreadcrumbs": "bottom"
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.22.2 (active)
angularjs, v0.3.5 (active)
atom-bootstrap3, v1.2.12 (inactive)
atom-handlebars, v1.3.0 (active)
atom-jade, v0.3.0 (active)
atom-json-color, v0.4.2 (active)
atom-lupa, v0.7.25 (active)
atom-monokai, v0.10.4 (inactive)
atom-nodejs-snippets, v1.2.0 (inactive)
atom-pair, v2.0.10 (active)
atom-ternjs, v0.16.0 (active)
autoclose-html, v0.23.0 (active)
autocomplete-modules, v1.6.7 (active)
autocomplete-paths, v1.0.2 (active)
code-stats-atom, v2.0.0 (active)
expressjs, v1.0.1 (inactive)
filesize, v2.0.0 (active)
fold-comments, v0.6.0 (inactive)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
html2jade-plus, v1.0.0 (inactive)
ionic-preview, v0.6.4 (inactive)
jade, v1.0.0 (inactive)
js-hyperclick, v1.9.0 (active)
language-c, v0.51.3 (inactive)
linter, v1.11.18 (active)
linter-jshint, v3.0.1 (active)
logo-file-icons, v1.2.0 (active)
Lucario, v2.0.0 (inactive)
markdown-toc, v0.4.1 (inactive)
monokai-solarized-dark, v0.1.1 (inactive)
open-recent, v5.0.0 (active)
pigments, v0.37.0 (active)
solarized-dark-ui, v0.3.1 (inactive)
swackets, v0.12.0 (active)
sync-settings, v0.7.2 (active)
tree-view-copy-relative-path, v1.0.1 (inactive)
tree-view-search-bar, v0.1.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (inactive)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (inactive)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by hex13** [comment]
`Not working with Atom v1.12.2`
You mean you upgraded Atom and it stopped working?

**Comment by amandeepmittal** [comment]
@hex13 Yes. I updated Atom and now atom-lupa package is not working.

**Comment by hex13** [comment]
Check now.

**Comment by amandeepmittal** [comment]
Working absolutely fine now. Cheers!
